# Generated by Django 6.0 on 2026-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSRRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=200)),
                ("trip_type", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("guests", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("organization", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
